os:
  - osx
  - linux
language: node_js
node_js:
  - '10'
  - '8'
  - '6'
branches:
  only:
    - master
cache: yarn
before_script:
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install xclip; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; sleep 3; fi'
